### ISSUE TITLE
Modulemanager can be uninstalled

### ISSUE THREAD

**Issue by IMcPwn** [hak5/lanturtle-files#6]
Currently, you can use modulemanager to uninstall itself. 

I see no use for removing modulemanager and someone who just highlights all the modules to delete them could have a rough time getting it back if they don't know it's located at /rom/etc/turtle/modules/modulemanager

I could come up with a fix, if you would like. I didn't make a pull request though as I'm not sure how far along you are with the new modulemanager.

**Comment by sebkinne** [comment]
Fixed, thanks!
